version: '3.3'

volumes:
  static_volume:
  media_volume:
  postgres_data:
  nginx_config:

services:
  db:
    container_name: postgres
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
     - ./.env

  web:
    container_name: foodgram
    image: 'vbuoc/foodgram:latest'
    # build: .
    restart: always
    command: gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000 --access-logfile -
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
      - nginx_config:/app/nginx/
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    container_name: nginx
    restart: always
    image: nginx:1.19-alpine
    volumes:
      - web-root:/var/www/html
      - static_volume:/app/static/
      - media_volume:/app/media/
      - nginx_config:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    ports:
      - 80:80
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email admin@foodgram.live --agree-tos --no-eff-email --staging -d foodgram.live  -d www.foodgram.live