version: '3.3'

volumes:
  static_volume:
  media_volume:
  postgres_data:

services:

  rabbitmq:
    hostname: rabbitmq
    container_name: rabbitmq
    restart: always
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  db:
    container_name: postgres
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
     - ./.env
    depends_on:
      - rabbitmq

  web:
    container_name: foodgram
    build: .
    restart: always
    command: gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000 --access-logfile -
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    env_file:
      - ./.env
    depends_on:
      - db

  celery_worker:
    container_name: celery_worker
    restart: always
    network_mode: host
    build:
      context: .
      dockerfile: worker/Dockerfile
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    env_file:
      - ./.env
    depends_on:
      - rabbitmq

  nginx:
    container_name: nginx
    restart: always
    #image: nginx:1.19-alpine
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    ports:
      - 80:80
    depends_on:
      - db
      - web
