version: '3.3'

volumes:
  static_volume:
  media_volume:
  postgres_data:

services:
  db:
    container_name: postgres
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
     - ./.env

  web:
    container_name: foodgram
    image: 'vbuoc/foodgram:latest'
    #build: .
    restart: always
    command: gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000 --access-logfile -
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    container_name: nginx
    restart: always
    #image: nginx:1.19-alpine
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    ports:
      - 80:80
    depends_on:
      - db
      - web
