# Generated by Django 3.2.2 on 2021-05-12 08:55

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=stdimage.models.StdImageField(blank=True, upload_to='recipes/'),
        ),
    ]
